import type { Metadata } from 'next'
import './globals.css'
import { Suspense } from 'react'
import Loading from './loading'
import CommonLayout from '@/components/common-layout'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'JobPortal',
  description: 'JobPortal Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <CommonLayout children={children} />
        </Suspense>
      </body>
    </html>
  )
}
